CREATE OR REPLACE PACKAGE user_package
AS
  FUNCTION create_user(
      NAME     VARCHAR2,
      email    VARCHAR2,
      PASSWORD VARCHAR2 )
    RETURN NUMBER;
END user_package;
/


CREATE OR REPLACE PACKAGE BODY USER_PACKAGE
AS
  NEW_USER  NUMBER;
  TOT_USERS NUMBER;
  FUNCTION CREATE_USER(
      NAME     VARCHAR2,
      EMAIL    VARCHAR2,
      PASSWORD VARCHAR2 )
    RETURN NUMBER
  IS
    TOT_USERS NUMBER;
  BEGIN
    SELECT USER_ID_SEQUENCE.NEXTVAL INTO NEW_USER FROM DUAL;
    INSERT
    INTO USERS
      (
        ID,
        NAME,
        EMAIL,
        PASSWORD
      )
      VALUES
      (
        NEW_USER,
        NAME,
        EMAIL,
        PASSWORD
      );
    SELECT COUNT(*) INTO TOT_USERS FROM USERS;
    RETURN(TOT_USERS);
  END;
END USER_PACKAGE;
/
